services:
  application:
    container_name: template_app
    build: ./
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - DB_HOST=template_mysql
      - DB_DATABASE=template
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 9501:9501
    volumes:
      - ./:/var/www

      # nginx pools configuration
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf

      # php-fpm socket
      - "phpsocket:/var/run"
    networks:
      - global-default
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: template_nginx
    image: nginx:1.25.2-alpine
    volumes:
      - ./:/var/www

      # nginx pools configuration
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf

      # php-fpm .conf's
      - ./.docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

      # php-fpm socket
      - "phpsocket:/var/run"
    ports:
      - "8080:80" # http
      # - "443:443" # https
    networks:
      - global-default
    depends_on:
      - application

  mysql:
    container_name: template_mysql
    image: mysql:8.1
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=template
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - global-default

  redis:
    container_name: template_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - global-default

volumes:
  mysql_db:
  phpsocket:

networks:
  global-default:
    external: true
